repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--skip-gitignore"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/FelixSeptem/pre-commit-golang
    rev: 12f5442f51377b10b26651ad745206bbe1500ad6
    hooks:
    - id: bazel-buildifier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
